server:
  port: 8333
spring:
  application:
    name: service-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-vod
          predicates: Path=/*/vod/**
          uri: lb://service-vod
        - id: service-order
          predicates: Path=/*/order/**
          uri: lb://service-order
        - id: service-user
          predicates: Path=/*/user/**
          uri: lb://service-user
        - id: service-activity
          predicates: Path=/*/activity/**
          uri: lb://service-activity
        - id: service-wechat
          predicates: Path=/*/wechat/**
          uri: lb://service-wechat
        - id: service-live
          predicates: Path=/*/live/**
          uri: lb://service-live
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
